name: Maven Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Gamble/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Gamble/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        working-directory: Gamble
        run: mvn -B clean package --file pom.xml

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: Gamble-plugin
          path: Gamble/target/*.jar
